# Project: bams_app
# Makefile created by Embarcadero Dev-C++ 6.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = bams.o bams_app.o merge.o bisect.o
LINKOBJ  = bams.o bams_app.o merge.o bisect.o
LIBS     = -L"C:/OLD_DISK/C_DISK/test/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib32" -static-libgcc -m32
INCS     = -I"C:/OLD_DISK/C_DISK/test/Dev-Cpp/TDM-GCC-64/include" -I"C:/OLD_DISK/C_DISK/test/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/OLD_DISK/C_DISK/test/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/OLD_DISK/C_DISK/test/Dev-Cpp/TDM-GCC-64/include" -I"C:/OLD_DISK/C_DISK/test/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/OLD_DISK/C_DISK/test/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/OLD_DISK/C_DISK/test/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = bams_app.exe
CXXFLAGS = $(CXXINCS) -ansi -m32 -w -Wall -Wextra
CFLAGS   = $(INCS) -ansi -m32 -w -Wall -Wextra
DEL      = del /f /q

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN) 2>nul

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

bams.o: bams.c
	$(CC) -c bams.c -o bams.o $(CFLAGS)

bams_app.o: bams_app.c
	$(CC) -c bams_app.c -o bams_app.o $(CFLAGS)

merge.o: merge.c
	$(CC) -c merge.c -o merge.o $(CFLAGS)

bisect.o: bisect.c
	$(CC) -c bisect.c -o bisect.o $(CFLAGS)
